CREATE DATABASE alemanac;

\c alemanac;

CREATE TABLE users (id SERIAL PRIMARY KEY, first_name varchar(25), last_name varchar(25), username varchar(25), email varchar(50), password_salt varchar(255), password_hash varchar (255));

CREATE TABLE entries (id SERIAL PRIMARY KEY, user_id INT references users(id), beer_id INT, notes text, vote INT, consume_location varchar(100), consume_date date, entry_date timestamp, is_custom boolean, beer_name varchar(30), brewery varchar(50), brew_location varchar(50), abv real);

CREATE TABLE beers (id SERIAL PRIMARY KEY, beer_id INT, name varchar(50), style varchar(50), brewery varchar(50), brew_location varchar(50), glass varchar(25), abv real, label_img varchar(255));

CREATE TABLE styles (id SERIAL PRIMARY KEY, beer_style_id INT, beer_style_name varchar(50));

INSERT INTO users (first_name, last_name, username, email, password_salt, password_hash) VALUES ('Joe','Wilson','joewilson','joe@gmail.com','1324','14223');

INSERT INTO users (first_name, last_name, username, email, password_salt, password_hash) VALUES ('Mary','Contrary','thatgirl','mary@yahoo.com','9324','22223');

INSERT INTO entries (user_id, beer_id, notes, vote, consume_location, consume_date, entry_date, is_custom, beer_name, brewery, brew_location, abv)
   VALUES (1, 2, 'I like this beer', 5, 'Chicago',2015-6-30,2015-7-31,TRUE,'Bud Light Lime','Budweiser','St. Louis',5);

INSERT INTO entries (user_id, beer_id, notes, vote, consume_location, consume_date, entry_date, is_custom, beer_name, brewery, brew_location, abv)
  VALUES (2, 5, 'It da bomb!', 2, 'Boston',2013-2-20,2014-2-1,TRUE,'Sam Adams Lager','Sam Adams','Boston',4.5);

INSERT INTO styles (beer_style_id, beer_style_name) VALUES (1,'English Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (2,'English IPA');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (3,'Bitter');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (4,'Special Bitter');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (5,'ESB');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (6,'English Summer Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (7,'Scottish Light');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (8,'Scottish Heavy');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (9,'Scottish Export');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (10,'English Pale Mild');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (11,'English Dark Mild');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (12,'English Brown');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (13,'Old Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (14,'Strong Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (15,'Scotch Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (16,'British Imperial Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (17,'British Barleywine');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (18,'Brown Porter');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (19,'Robust Porter');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (20,'Sweet Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (21,'Oatmeal Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (163,'Double Red');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (165,'Contemporary Gose');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (22,'Irish Red');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (23,'Dry Irish Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (24,'Export Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (25,'American Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (26,'Wet Hop Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (27,'American Belgian Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (28,'American Belgian Dark');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (29,'American Strong Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (30,'American IPA');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (31,'Imperial IPA');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (32,'Amber');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (33,'Imperial Red');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (34,'American Barleywine');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (35,'Wheatwine');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (36,'Blonde');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (37,'American Brown');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (38,'Smoke Porter');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (40,'Sour');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (41,'Black Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (42,'American Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (43,'American Imperial Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (44,'Stout');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (158,'American Imperial Porter');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (164,'Session IPA');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (45,'Kolsch');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (46,'Berlinerweisse');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (47,'Leipzig Gose');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (48,'Hefeweizen');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (49,'Kristallweizen');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (50,'Leichtesweizen');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (51,'Bernsteinfarbenesweizen');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (52,'Dunkelweizen');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (53,'Weizenbock');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (54,'Rauchbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (55,'Altbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (56,'Kellerbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (159,'Adambier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (57,'Flanders Red');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (58,'Belgian Dubbel');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (59,'Belgian Tripel');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (60,'Belgian Quad');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (61,'Belgian Blonde');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (62,'Belgian Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (63,'Belgian Pale Strong');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (64,'Belgian Dark Strong');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (65,'Witbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (66,'Lambic');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (67,'Gueuze');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (68,'Fruit Lambic');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (69,'Belgian Table Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (70,'Belgian Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (71,'Biere de Garde');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (72,'Saison');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (73,'International Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (74,'Austrailian Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (75,'German Pilsener');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (76,'Bohemian Pilsener');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (77,'Leichtbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (78,'Helles');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (79,'Dortmunder');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (80,'Vienna Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (81,'Marzen');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (82,'Oktoberfest');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (83,'Euro Dark');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (84,'Schwarzbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (85,'Marzen Rauchbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (86,'Helles Rauchbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (87,'Bock Rauchbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (88,'Bock');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (89,'Maibock');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (90,'Doppelbock');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (91,'Eisbock');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (92,'Kellerbier');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (93,'American Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (94,'American Light Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (95,'American Low-Carb Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (96,'American Amber Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (97,'American Premium Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (98,'American Pilsener');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (99,'American Ice Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (100,'Malt Liquor');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (101,'American Amber Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (102,'American Oktoberfest');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (103,'American Dark Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (104,'Baltic Porter');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (105,'Tropical Light Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (106,'International Pilsener');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (107,'Dry Lager');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (39,'Brett');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (108,'Session');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (109,'Cream Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (110,'California Common');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (111,'Gingo-Sake');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (112,'Wheat Ale with Yeast');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (113,'Wheat Ale (No Yeast)');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (114,'Fruit Wheat Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (115,'Dark Wheat Ale with Yeast');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (116,'Dark Wheat Ale (No Yeast)');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (117,'Rye Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (118,'German Rye');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (119,'Fruit Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (120,'Field Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (121,'Pumpkin Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (122,'Chocolate Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (123,'Coffee Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (124,'Spice Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (125,'Specialty');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (126,'Honey Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (127,'Gluten-Free Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (128,'Indigenous Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (129,'Smoke Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (130,'Experimental Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (131,'Traditional');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (132,'BBL Aged');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (133,'BBL Aged Pale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (134,'BBL Aged Dark');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (135,'BBL Aged Strong');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (136,'BBL Aged Sour');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (137,'Aged Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (138,'Strong Ale');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (139,'Non-Alcoholic');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (167,'Belgian Fruit');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (168,'Chili Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (169,'Mixed Brett');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (170,'Wild Beer');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (140,'Dry Mead');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (141,'Semi-Sweet Mead');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (142,'Sweet Mead')
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (143,'Cyser');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (144,'Pyment');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (145,'Fruit Melomel');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (146,'Metheglin');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (147,'Braggot');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (148,'Mead');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (149,'Common Cider');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (150,'English Cider');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (151,'French Cider');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (152,'Common Perry');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (153,'Traditional Perry');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (154,'New England Cider');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (155,'Fruit Cider');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (156,'Apple Wine');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (157,'Specialty Cider');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (160,'Grodziskie');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (166,'Dutch Kuit');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (161,'Flavored Malt Beverage');
INSERT INTO styles (beer_style_id, beer_style_name) VALUES (162,'Energy Malt Beverage');
